-
 name: "This play gathers folder info"
 hosts: localhost
 tasks:
  - name: Provide information about vCenter folders
    community.vmware.vmware_folder_info:
     hostname: '{{ vcenter_hostname }}'
     username: '{{ vcenter_username }}'
     password: '{{ vcenter_password }}'
     datacenter: datacenter_name
    delegate_to: localhost
    register: vcenter_folder_info

  - name: Get information about folders
    community.vmware.vmware_folder_info:
     hostname: '{{ vcenter_hostname }}'
     username: '{{ vcenter_username }}'
     password: '{{ vcenter_password }}'
     datacenter: 'Asia-Datacenter1'
    register: r

  - name: Set Managed object ID for the given folder
    ansible.builtin.set_fact:
     folder_mo_id: "{{ (r.flat_folder_info | selectattr('path', 'equalto', '/Asia-Datacenter1/vm/tier1/tier2') | map(attribute='moid'))[0] }}"
